name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 检查Git代码
        uses: actions/checkout@v4

      - name: 前置DockerBuild
        uses: docker/setup-buildx-action@v3

      - name: 登录Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: 生成镜像标签
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: consistentlee/vod_next
          tags: |
            type=raw,value=latest
            type=ref,event=tag

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置Buildx
        uses: docker/setup-buildx-action@v2

      - name: 构建并推送镜像
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max